#on: [push]
on:
 workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: convictional/trigger-workflow-and-wait@v1.6.1
      with:
          owner: BranchMetrics
          repo: qentelli-saas-sdk-testing-automation
          github_token: ${{ secrets.BRANCHLET_ACCESS_TOKEN_PUBLIC }}
          workflow_file_name: ios-maven.yml
          ref: 'master'
          wait_interval: 10
          client_payload: '{}'
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true
    - name: Fetching test report from automation suite
      if: always()
      uses: dawidd6/action-download-artifact@v2
      with:
       github_token: ${{ secrets.BRANCHLET_ACCESS_TOKEN_PUBLIC }}
       repo: BranchMetrics/qentelli-saas-sdk-testing-automation
       workflow: ios-maven.yml
       workflow_conclusion: ""
       branch: master
       name: test-results
       check_artifacts:  true
       search_artifacts:  true
       skip_unpack: false
       
    - name: Display S3 url
      if: always()
      run: grep 'Test report file link' output.txt
