on:
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.BRANCHLET_ACCESS_TOKEN_PUBLIC  }}
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: 'BranchMetrics',
            repo: 'qentelli-saas-sdk-testing-automation',
            workflow_id: 'maven.yml',
            ref: 'master'
          })
